### ISSUE TITLE
Tests failing on ddmrp_adjustment

### ISSUE THREAD

**Issue by grindtildeath** [ForgeFlow/ddmrp#65]
Hello
Since https://github.com/Eficent/ddmrp/commit/7cb743c5a2513168f68867644d5a67f7eaf46085, this test is failing : https://github.com/Eficent/ddmrp/blob/11.0/ddmrp_adjustment/tests/test_adu_dlt_adjustment.py#L13

What should we do in this case ? 

We did ping @lreficent on the commit, but no answer.

**Comment by LoisRForgeFlow** [comment]
@grindtildeath sorry for the delay, I answered you on that commit. This should be fixed soon.

**Comment by LoisRForgeFlow** [comment]
But the only thing that you should do in test is to explicitly call the adu cron action, as it is not automatic anymore.

**Comment by grindtildeath** [comment]
@lreficent Thanks for the update. So let's wait until the end of the week that CS is finish to port the branch to OCA.

**Comment by LoisRForgeFlow** [comment]
We are also waiting this PR to be updated: https://github.com/OCA/manufacture/pull/254. And also FYI we are preparing an update on de main ddmrp module, but I hope this will be proposed soon.

**Comment by LoisRForgeFlow** [comment]
Last travis build was green including tests so I close this

**Comment by grindtildeath** [comment]
@lreficent Thanks for fixing. I just pushed all the changes to OCA here : https://github.com/OCA/ddmrp/pull/3

**Comment by LoisRForgeFlow** [comment]
@grindtildeath We are still not ready to move to OCA unfortunately. We are still working on some important improvements you can follow here: https://github.com/Eficent/ddmrp/pull/69

**Comment by guewen** [comment]
@lreficent We can't keep up with the update of the OCA pull request.

Which do you prefer? 
1. we stop updating the OCA move and you do it once you are done
2. we all decide that from now the OCA one is the reference and you move your pull request on the OCA one

Honestly I would prefer the second option because the move is always delayed, but that's your call.

**Comment by LoisRForgeFlow** [comment]
@guewen I understand it and it is totally reasonable. I rather the first option though, because the data model is changing in this last change. I also agree that the move is delaying a lot, so I commit myself to propose the move within the next 2 weeks, so feels free to close the current PR to OCA/ddmrp as I will open a new one.

Thank you guys for keeping it updated until now anyway!
